env: development
secret: b7xd9s8f6g4h2j0
storage_path: "./storage/userservice.db"
grpc:
  port: 55055
  timeout: 10h
kafka:
  brokers:
    - "kafka:9092"
  topic: "sso_events"
  group_id: "user-service-group"
  dial_addr: "kafka:9092"
metrics:
  port: 8082
  host: 0.0.0.0